### ISSUE TITLE
Data Behind

### ISSUE THREAD

**Issue by Skekacs93** [usgpo/bulk-data#10]
HR 6297 was introduced Monday (11/14), but hasn't appeared yet at https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr.

**Comment by llaplant** [comment]
We are currently processing all existing and new 114th bill status files to make sure new fields are available for the entire data set. Data will continue to be updated throughout the day and night. Estimate is 2 days to complete all updates. Apologize for the delays.
