### ISSUE TITLE
Supreme Court Decisions - FLITE DB - Data Missing 

### ISSUE THREAD

**Issue by danieldjewell** [usgpo/bulk-data#107]
Hello US GPO Team!

It appears that Supreme Court Opinions data for years other than 1937 is missing from the bulk data repository (https://www.govinfo.gov/bulkdata/SCD) ... 

Given that SCOTUS's own links to this data are broken (https://www.supremecourt.gov/opinions/obtainopinions.aspx linking to FDsys and http://supcourt.ntis.gov), it doesn't appear that this is available anywhere else...

Thank you!

**Comment by Firmanfoc94** [comment]
> Hello US GPO Team!
> 
> It appears that Supreme Court Opinions data for years other than 1937 is missing from the bulk data repository (https://www.govinfo.gov/bulkdata/SCD) ...
> 
> Given that SCOTUS's own links to this data are broken (https://www.supremecourt.gov/opinions/obtainopinions.aspx linking to FDsys and http://supcourt.ntis.gov), it doesn't appear that this is available anywhere else...
> 
> Thank you!

Vote

**Comment by jonquandt** [comment]
Sorry for the delay in responding. 

We currently only have the 1937 data in the bulk data repository. You may wish to look at the [U.S. Reports data](https://www.loc.gov/collections/united-states-reports/about-this-collection/) available from the Library of Congress, covering 1754-2012
