### ISSUE TITLE
Extra action on 117 S 1048

### ISSUE THREAD

**Issue by avalatea** [usgpo/bulk-data#109]
Hi! It looks like there are some extra actions for the above noted [bill](https://www.govinfo.gov/bulkdata/BILLSTATUS/117/s/BILLSTATUS-117s1048.xml).

<img width="1280" alt="Screen Shot 2022-10-17 at 8 28 35 AM" src="https://user-images.githubusercontent.com/107426303/196227028-cf381d4c-7c0b-4d55-90d8-c82567408d2a.png">

This action is neither shown [here](https://www.congress.gov/bill/117th-congress/senate-bill/1048/actions?r=18&s=1) or [here](https://www.govinfo.gov/app/details/BILLS-117s1048is/related).

Can we confirm if the xml information is a mistake? There could also be more mistakes as well, and I'll add them onto this issue if I find them.

**Comment by jonquandt** [comment]
Good afternoon,

Please take another look - we regenerated the file from the source and I am no longer seeing those extra actions.

**Comment by avalatea** [comment]
Yes this has been fixed! Thank you!
