### ISSUE TITLE
/bulkdata/CFR/2016/ xml files have no style sheet

### ISSUE THREAD

**Issue by robstryker** [usgpo/bulk-data#11]
When browsing HR's via the web interface of the bulk data (ex:  https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/hr/BILLS-115hr71rfs.xml)   the xml file will appear in a readable format thanks to the stylesheet. 

When browsing https://www.gpo.gov/fdsys/bulkdata/CFR/2016/title-32/CFR-2016-title32-vol6.xml no stylesheet is included, which makes it difficult to read.

**Comment by llaplant** [comment]
Thank you for the suggestion. You may want to check out the XML file on FDsys. It includes a stylesheet. https://www.gpo.gov/fdsys/pkg/CFR-2016-title32-vol6/xml/CFR-2016-title32-vol6.xml and https://www.gpo.gov/fdsys/browse/collectionCfr.action?collectionCode=CFR. We will keep your suggestion in mind as we migrate FDsys bulk data functionality to www.govinfo.gov.

**Comment by robstryker** [comment]
If there are other pages that do include the stylesheet, then it seems you are duplicating data somewhere ;)  That might be worth cleaning up or unifying in some fashion.

**Comment by llaplant** [comment]
Data is being served from the same source.
