### ISSUE TITLE
Missing HR 3241

### ISSUE THREAD

**Issue by avalatea** [usgpo/bulk-data#111]
Hi y'all! Thank you so much for the great help last time.

I'm here to ask about HR3241, which I cannot find from this [Bulk Data list](https://www.govinfo.gov/bulkdata/BILLS/117/1/hr). But according to Congress, [it does exist](https://www.congress.gov/bill/117th-congress/house-bill/3241). Is there a reason it's not part of the bulk data?

**Comment by llaplant** [comment]
H.R. 3241 is a codification measure for the U.S. Code. It is available in text and PDF formats, but it is not available in XML. https://www.govinfo.gov/app/details/BILLS-117hr3241ih/summary. For reference, Congress.gov maintains a list of data anomalies https://www.congress.gov/help/data-anomalies.
