### ISSUE TITLE
Bill number/type codes

### ISSUE THREAD

**Issue by zpneal** [usgpo/bulk-data#113]
In the 116th session and earlier bill status files, a bill's number and type are noted with the XML tags <billNumber> and <billType> respectively. But, starting in the 117th session these were shortened to <number> and <type>. I couldn't find any documentation of this change, but discovered it due to an error in introduced in a parsing script.

**Comment by jonquandt** [comment]
Could you enclose the tag information you have below

>were shortened to and . 

into code blocks so we can better understand the issue? 

This may be a result of https://github.com/usgpo/bill-status/issues/200, where we adopted a new version of our upstream source for BILLSTATUS and BILLSUM information, the congress.gov API.

**Comment by zpneal** [comment]
Sorry about that. In the 116th and earlier, the tags `<billNumber>` and `<billType>` are used ([example](https://www.govinfo.gov/bulkdata/BILLSTATUS/116/sjres/BILLSTATUS-116sjres37.xml)). Starting in the 117th they changed to `<number>` and `<type>` ([example](https://www.govinfo.gov/bulkdata/BILLSTATUS/117/sjres/BILLSTATUS-117sjres33.xml)). I see now that the change was noted in the issue you linked. Thanks!
