### ISSUE TITLE
Some data anomolies for HR 27

### ISSUE THREAD

**Issue by avalatea** [usgpo/bulk-data#114]
Hi! Want to report that [HR 27](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr27.xml) does not currently have [Jake Ellzey](https://www.congress.gov/bill/118th-congress/house-bill/27/cosponsors?q=%7B%22search%22%3A%5B%22actionSessionChamber%3A118-1%7CH+AND+%28billIsReserved%3A%5C%22N%5C%22+OR+type%3A%5C%22AMENDMENT%5C%22%29%22%2C%22118-1%7CH%22%5D%7D&r=8&s=3) as a co-sponsor. Will they be added in the future?

**Comment by llaplant** [comment]
Good afternoon, when additional sponsors or cosponsors are added to Congress.gov, the data will flow through to the BILLSTATUS XML bulk data file on GovInfo.gov. You may also want to check out the Congress.gov API https://github.com/LibraryOfCongress/api.congress.gov/.

**Comment by llaplant** [comment]
@aweiss27 could you take a look at this issue? It may be more in scope for Congress.gov. [HR 27](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr27.xml) does not currently have [Jake Ellzey](https://www.congress.gov/bill/118th-congress/house-bill/27/cosponsors?q=%7B%22search%22%3A%5B%22actionSessionChamber%3A118-1%7CH+AND+%28billIsReserved%3A%5C%22N%5C%22+OR+type%3A%5C%22AMENDMENT%5C%22%29%22%2C%22118-1%7CH%22%5D%7D&r=8&s=3) as a co-sponsor.

**Comment by aweiss27** [comment]
Yes, I'll look into this @llaplant!

**Comment by aweiss27** [comment]
Rep. Jake Ellzey is present as a cosponsor of 118 HR27 in the [Congress.gov API](https://api.congress.gov/v3/bill/118/hr/27/cosponsors?api_key=DEMO_KEY&limit=30). Can the bill status XML file for 118 HR27 be reprocessed to see if that brings him in @llaplant?

**Comment by llaplant** [comment]
Reviewing issues. @avalatea could you verify https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr27.xml for Ellzey and if okay close issue? Thanks!

**Comment by avalatea** [comment]
Yupp. We can confirm that this has been resolved! Thank you!
