### ISSUE TITLE
CFR - missing images (title 7)

### ISSUE THREAD

**Issue by lkp80877984** [usgpo/bulk-data#115]
Hi!

It seems that the following images are missing from the images zip for title 7:

![image](https://user-images.githubusercontent.com/107598242/212199015-5d30d786-419b-4ccf-9d9f-2b3828580a62.png)

/graphics/er27de22.038.gif
/graphics/er27de22.039.gif
/graphics/er27de22.040.gif

Cheers!

**Comment by llaplant** [comment]
Please take a look at the eCFR bulk data files to see if this meets your needs. There is a ZIP file of images for Title 7 https://www.govinfo.gov/bulkdata/ECFR/title-7

**Comment by lkp80877984** [comment]
Thanks, Lisa! That's the .zip of images that I'm looking at. It is missing images with names like er27*.

Cheers,
Luke

**Comment by llaplant** [comment]
Got it. Working on this.

**Comment by llaplant** [comment]
@lkp80877984 please check now. https://www.govinfo.gov/bulkdata/ECFR/title-7/

**Comment by lkp80877984** [comment]
Thanks, Lisa! :)
