### ISSUE TITLE
Extra page in documents HR26

### ISSUE THREAD

**Issue by avalatea** [usgpo/bulk-data#116]
Hi, in HR26, I see that there is an extra page at the end. Is this supposed to be there? If it is, can it be rotated so that it is upright?

<img width="600" alt="Screen Shot 2023-01-24 at 1 35 25 PM" src="https://user-images.githubusercontent.com/107426303/214426155-c82939a2-cb26-49f3-803c-048c26efca63.png">

**Comment by llaplant** [comment]
Thank you for your question. Yes, it is intentional, and it is an artifact of the print production process.

**Comment by avalatea** [comment]
Thanks for the quick response @llaplant ! Just a small followup: is there an update on [this issue](https://github.com/usgpo/bulk-data/issues/114)? It appears to be on-going.
