### ISSUE TITLE
CFR (Annual Edition), 2022 - Title 7, has inconsistent file names for Volume which are sometimes Padded

### ISSUE THREAD

**Issue by haysclark** [usgpo/bulk-data#117]
### Summary

BulkDate for [2022 - Title 7](https://www.govinfo.gov/bulkdata/CFR/2022/title-7) has inconsistent file names for some of the volumes. Offending files have Volume Numbers that are padded. (e.g. `CFR-2022-title7-vol03.xml` vs `CFR-2022-title7-vol3.xml`)

### Steps to reproduce the behavior

- Navigate to: https://www.govinfo.gov/bulkdata/CFR/2022/title-7
- see list of names

### Expected behavior
- All file names should be consistent
- File names should match naming schemes used in previous years and not be padded - example: [2021-title7](https://www.govinfo.gov/bulkdata/CFR/2021/title-7)

### Actual behavior
Inconsistent naming scheme:
- `CFR-2022-title7-vol03.xml`
- `CFR-2022-title7-vol06.xml`

vs.

- `CFR-2022-title7-vol5.xml`

### Screenshot
![image](https://user-images.githubusercontent.com/138324/214427093-f62b663d-d6ce-463a-94a4-f026a3c92c89.png)

**Comment by llaplant** [comment]
Fixed! https://www.govinfo.gov/bulkdata/CFR/2022/title-7
