### ISSUE TITLE
Text for HR 813

### ISSUE THREAD

**Issue by jgint** [usgpo/bulk-data#118]
Hi, I'm expecting to find the text for HR 813 from the 2023-2024 regular session here https://www.govinfo.gov/bulkdata/BILLS/118/1/hr/BILLS-118hr813ih.xml but that file doesn't seem to exist.

This data does exist on the source website, though:
- Bill info page [https://www.congress.gov/bill/118th-congress/house-bill/813?q={"search"%3A["HR+813"]}&s=1&r=1](https://www.congress.gov/bill/118th-congress/house-bill/813?q=%7B%22search%22%3A%5B%22HR+813%22%5D%7D&s=1&r=1)
- Document page https://www.congress.gov/118/bills/hr813/BILLS-118hr813ih.xml

Is the above the correct place to find the text, or is there some other reason behind the discrepancy? Thanks in advance!

**Comment by avalatea** [comment]
@llaplant Is there an update on this? It looks like there is still no link for HR813.
<img width="800" alt="Screen Shot 2023-04-06 at 7 54 11 AM" src="https://user-images.githubusercontent.com/107426303/230417600-8e6f299a-cbbc-4b6b-a334-f580efeb593c.png">

**Comment by llaplant** [comment]
GPO is anticipating a replacement file from the House. Upon receipt, the file will be made available on GovInfo at https://www.govinfo.gov/bulkdata/BILLS/118/1/hr/BILLS-118hr813ih.xml and then on Congress.gov at https://www.congress.gov/118/bills/hr813/BILLS-118hr813ih.xml.

**Comment by llaplant** [comment]
File is available https://www.govinfo.gov/bulkdata/BILLS/118/1/hr/BILLS-118hr813ih.xml
