### ISSUE TITLE
Question on knowing the order of revisions of a given HR bill

### ISSUE THREAD

**Issue by robstryker** [usgpo/bulk-data#13]
While browsing:  https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/hr

I see the following entries (subset):

BILLS-115hr70eh.xml 	06-Jan-2017 03:32 	0.04 M
BILLS-115hr70ih.xml 	04-Jan-2017 05:23 	0.04 M
BILLS-115hr70rfs.xml 	07-Jan-2017 05:00 	0.04 M

While via the UI I can guess via the timestamps as to which is newest, there does not appear to be a programatic way to do so.  The suffixes (eh, ih, rfs) seem random and arbitrary, and the user guide for BILLS does not indicate what the suffixes mean, or if there's any way to tell what order the revisions are. 

I would suppose I could tell by timestamp, but, as mentioned above, that's only visible in the UI of the website.  If I were to download the zip file,  BILLS-115-1-hr.zip,  all of the files have the exact same timestamp with each other. 

Even more strange, it is now 11PM EST on Tuesday, January 10th,  but all of the files in the BILLS-115-1-hr.zip file that I just downloaded right now have a timestamp of January 11th, 2017, 3:44am, which is in the future for me. So I would imagine your server or build machine that generates the zips is somewhere many hours in the future (England?) or has an incorrect system clock. 

It might be reasonable to have your build machine preserve timestamps of the files when generating the zips. 

I now see that <dc:date>2017-01-05</dc:date> is in the XML, however, some files have that tag empty. (See view-source:https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/hr/BILLS-115hr70eh.xml).  Is it fair to assume that an empty tag means 'initial revision' ?  Perhaps this should be documented. 

Final Question:  Once the ammendment process begins, is a new revision generated for each new ammendment? Or is it one new revision / xml file generated per day, regardless of number of ammendments approved?

**Comment by llaplant** [comment]
You may want to check out the FDsys bulk data sitemaps for update dates and times. The top-level bulk data sitemap is available at https://www.gpo.gov/smap/bulkdata/sitemapindex.xml and times are in UTC. 

The ZIP file is updated each time an update is made to the data set, hence all of the files inside of the ZIP file have the same timestamp. 

You may also want to take a look at the BILLSTATUS data set which is available at https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS for more information about each legislative measure. The UI for the BILLSTATUS dataset is presented via www.congress.gov. 

The Federal legislative process is rather complex. Here are some resources you may want to check out. 

- The Legislative Process - https://www.congress.gov/legislative-process
- How Our Laws Are Made - http://www.gpo.gov/fdsys/pkg/CDOC-110hdoc49/pdf/CDOC-110hdoc49.pdf and https://www.congress.gov/resources/display/content/How+Our+Laws+Are+Made+-+Learn+About+the+Legislative+Process
- Common Bill Versions - http://www.gpo.gov/help/index.html#about_congressional_bills.htm. Legislation may be changed or amended as it makes its way through the legislative process. A new "revision" is generate for each bill version that is ordered to be printed. Note that bill status steps do not always correspond directly to bill versions. 
- Legislative Status Steps - http://www.loc.gov/pictures/resource/ppmsca.33996

Please let me know if you have additional questions or if you would like more information.
