### ISSUE TITLE
Senate Digest 11/13 and 11/14

### ISSUE THREAD

**Issue by TimTCM** [usgpo/bulk-data#138]
Regarding the Congressional Record so far this week for the Senate, Monday the Senate recessed instead of adjourning, and then had a brief session afterwards last night.

https://www.govinfo.gov/app/collection/crec/2023/11/11-13/2/DAILYDIGEST
https://www.govinfo.gov/app/collection/crec/2023/11/11-14/3/DAILYDIGEST

The Senate Digest pages for [11/13](https://www.govinfo.gov/content/pkg/CREC-2023-11-13/html/CREC-2023-11-13-pt2-PgD1173.htm) and [11/14](https://www.govinfo.gov/content/pkg/CREC-2023-11-14/html/CREC-2023-11-14-pt1-PgD1173.htm) are now showing identical content with the exception of a date difference in the top line.

The original Senate Digest page for 11/13 is now gone from GPO and only available (for now?) on [LOC](https://www.congress.gov/congressional-record/volume-169/issue-187/daily-digest/article/D1165-1).

**Is it possible to put the original 11/13 Senate Digest page back into the spot Senate Digest page spot for 11/13?** It has content that is not in the 11/14 version.

**Comment by jonquandt** [comment]
We're looking into this.

**Comment by jonquandt** [comment]
This should now be resolved. Note that there is also a https://www.govinfo.gov/app/details/CREC-2023-11-14-i189 issue now that contains the Senate session from 11/14.
