### ISSUE TITLE
House 12/14 order reversed

### ISSUE THREAD

**Issue by TimTCM** [usgpo/bulk-data#143]
The Clerk of the House had two items yesterday listed in this order:
https://clerk.house.gov/FloorSummary?date=12/14/2023

1:53:52 p.m. - United States Group of the NATO Parliamentary Assembly - Pursuant to 22 U.S.C. 1928a, and the order of the House of January 9, 2023, the Speaker appointed the following member of the House to the United States Group of the NATO Parliamentary Assembly: Mr. Norcross.

1:54:17 p.m. - Board of Trustees of the Institute of American Indian and Alaska Native Culture and Arts Development - Pursuant to 20 U.S.C. 4412, and the order of the House of January 9, 2023, the Speaker appointed the following members of the House to the Board of Trustees of the Institute of American Indian and Alaska Native Culture and Arts Development: Mr. Cole and Ms. Leger Fernandez.

The Record has them in this order:
https://www.govinfo.gov/app/collection/crec/2023/12/12-14/5/HOUSE

APPOINTMENT OF MEMBERS TO THE BOARD OF TRUSTEES OF THE INSTITUTE OF AMERICAN INDIAN AND ALASKA NATIVE CULTURE AND ARTS DEVELOPMENT  (H6981-2)

APPOINTMENT OF MEMBER TO THE UNITED STATES GROUP OF THE NATO PARLIAMENTARY ASSEMBLY  (H6981-3)

I'm not sure which is correct.

The audio may clarify once it becomes available:
https://live.house.gov/?date=2023-12-14

**Comment by jonquandt** [comment]
Good morning - following up on this - it appears that the version in our Congressional Record browse is matching the Clerk Floor summary order:

- 169 Cong. Rec. H6981  - APPOINTMENT OF MEMBER TO THE UNITED STATES GROUP OF THE NATO PARLIAMENTARY ASSEMBLY 
- 169 Cong. Rec. H6981 - APPOINTMENT OF MEMBERS TO THE BOARD OF TRUSTEES OF THE INSTITUTE OF AMERICAN INDIAN AND ALASKA...
