### ISSUE TITLE
FR/ECFR - ndash character in XML - change to hyphen

### ISSUE THREAD

**Issue by jonquandt** [usgpo/bulk-data#149]
NARA’s Office of the Federal Register and GPO are planning a change to how certain dash characters are presented in the XML for Federal Register and the Electronic Code of Federal Regulations.

## Change Summary
instances of en dashes (–) will be replaced by hyphens (-).

This will affect the following:

    Federal Register XML
    Electronic Code of Regulations XML

In the following locations:

    GovInfo (bulkdata repository, API, and general content access)
    federalregister.gov
    ecfr.gov 

Samples of current and updated XML are available [here](https://github.com/usgpo/bulk-data/tree/main/ndash-changes-March2024)
 
This change will go live on govinfo.gov, federalregister.gov, and ecfr.gov for new and updated content starting approximately on 3/26/2024.
 
This will initially affect new content within GovInfo, but will also be propagated to older content over time.

**Comment by yahyafurkann** [comment]
FR/ICFR

**Comment by yahyafurkann** [comment]
XML/CFR

**Comment by jonquandt** [comment]
These changes are now live for new and updated packages. We will be reprocessing the complete collection over the next several weeks
