### ISSUE TITLE
[QUESTION] is the XML Schema available for FRCFR/ECFR?

### ISSUE THREAD

**Issue by krannnn** [usgpo/bulk-data#150]
Dear,

I can't find the XML Schema (XSD file) of FRCFR/ECFR.
In [2.5. PREAMBLE Tag of FR XML User Guide](https://github.com/usgpo/bulk-data/blob/main/FR-XML_User-Guide.md#25-preamble-tag)

> The PREAMBLE can hold contents that describe the current page of the document as well as agencies, sub agencies, actions, summaries, RIN numbers, and CFR citations. In general, a preamble tag can hold everything up to but not including the supplementary information. To view a complete list of valid fields, **please see the XSD schema.**

However, I can't see any link to the XSD schema.

The XML user guides were last updated 3 years ago. Are these still up to date and reflect the latest publications?

Thank you

**Comment by jonquandt** [comment]
Hello,

The schemas are available in the bulk data repository in the resources area for each collection.

Here is the FR schema

https://www.govinfo.gov/bulkdata/FR/resources/FRMergedXML.xsd

CFR Schema

https://www.govinfo.gov/bulkdata/CFR/resources/CFRMergedXML.xsd

I am not aware of any significant changes to either schema in a number of years, so the user guides should still be accurate.

**Comment by krannnn** [comment]
Appreciate the prompt response. I was lost in the Github repos trying to find the same.
Closing the issue, many thanks!
