### ISSUE TITLE
3/26 CREC MODS: Ohio Senate resolution cited as U.S. Senate resolution

### ISSUE THREAD

**Issue by TimTCM** [usgpo/bulk-data#156]
The [mods](https://www.govinfo.gov/metadata/granule/CREC-2024-03-26/CREC-2024-03-26-pt1-PgH2120/mods.xml) granule for this page ([TXT](https://www.govinfo.gov/content/pkg/CREC-2024-03-26/html/CREC-2024-03-26-pt1-PgH2120.htm), [PDF](https://www.govinfo.gov/content/pkg/CREC-2024-03-26/pdf/CREC-2024-03-26-pt1-PgH2120.pdf), [Detail](https://www.govinfo.gov/app/details/CREC-2024-03-26/CREC-2024-03-26-pt1-PgH2120)) cites [S.Res. 196](https://www.congress.gov/bill/118th-congress/senate-resolution/196/all-actions) which is a “resolution recognizing the cultural and historical significance of the Cinco de Mayo holiday” and that does not seem to be related to “urging the United States Congress to amend the Railway Safety Act of 2023 to require rail shippers to secure all rail cars carrying solid waste to prevent littering and to create a study committee to analyze the benefits of securing rail cars carrying solid waste” ([Ohio Senate Resolution 196](https://www.legislature.ohio.gov/legislation/135/sr196)).

**Comment by jonquandt** [comment]
We have removed the reference from the metadata for this granule.
