### ISSUE TITLE
Pre-Introduced XML Bill Text Associated with S. 448 (Introduced on 2/27/17)

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bulk-data#16]
Hello, the XML/HTML version of S. 448 is the pre-introduced bill text, and is causing some problems: DTD: https://www.congress.gov/bill/115th-congress/senate-bill/448/text

It looks like the xml file in the bulk data repository is still the pre-introduced text, even though the bill was introduced on 2/27/17: https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/s/BILLS-115s448is.xml

The PDF version of the bill text has the correct number and introduction date associated with it: https://www.congress.gov/115/bills/s448/BILLS-115s448is.pdf

Is there any way you could update the bill text XML to the introduced text file and not the pre-introduced file? Thank you!

**Comment by llaplant** [comment]
Thank you for letting us know! We are correcting and will make the updated file available.

**Comment by llaplant** [comment]
Fixed!
