### ISSUE TITLE
Speaker missing in mods

### ISSUE THREAD

**Issue by TimTCM** [usgpo/bulk-data#161]
Speaker missing in the mods for this article:
GPO [mods](https://www.govinfo.gov/metadata/granule/CREC-2024-05-16/CREC-2024-05-16-pt1-PgH3286-2/mods.xml) ([TXT](https://www.govinfo.gov/content/pkg/CREC-2024-05-16/html/CREC-2024-05-16-pt1-PgH3286-2.htm), [PDF](https://www.govinfo.gov/content/pkg/CREC-2024-05-16/pdf/CREC-2024-05-16-pt1-PgH3286-2.pdf), [Detail](https://www.govinfo.gov/app/details/CREC-2024-05-16/CREC-2024-05-16-pt1-PgH3286-2))

**Comment by jonquandt** [comment]
Ms. De La Cruz has been added to the MODS record, please let me know if you see any issues.

**Comment by TimTCM** [comment]
Looks good. Thank you.

**Comment by TimTCM** [comment]
Same speaker is missing again in yesterday's Record: GPO [mods](https://www.govinfo.gov/metadata/granule/CREC-2024-06-04/CREC-2024-06-04-pt1-PgH3586/mods.xml) ([TXT](https://www.govinfo.gov/content/pkg/CREC-2024-06-04/html/CREC-2024-06-04-pt1-PgH3586.htm), [PDF](https://www.govinfo.gov/content/pkg/CREC-2024-06-04/pdf/CREC-2024-06-04-pt1-PgH3586.pdf), [Detail](https://www.govinfo.gov/app/details/CREC-2024-06-04/CREC-2024-06-04-pt1-PgH3586))

**Comment by jonquandt** [comment]
metadata has been updated. Looking at how we can improve parsing for this Member in the Record. It looks like in these two instances, the text has her listed as `Ms. De La CRUZ` instead of `Ms. DE LA CRUZ`
