### ISSUE TITLE
Publishing time estimate

### ISSUE THREAD

**Issue by TimTCM** [usgpo/bulk-data#162]
When the _Congressional Record_ comes out each day can really vary. It can be somewhat predictable based on Congress' schedule from the day before or its closeness to the end of a work period, but that still only gives a broad range, not a precise time.

Would it be possible to publish somewhere when processing on it was started and an estimate of how long it will take for the _Record_ to be released each day, or an estimate of when it would be released?

Thank you,
Tim
17,153 days

**Comment by jonquandt** [comment]
@TimTCM  - the Congressional Record comes from multiple sources and the GovInfo team does not have reliable insight into when files will be submitted to GovInfo for online publication, so we cannot fulfill this request at this time.

**Comment by TimTCM** [comment]
Thank you, Jon.

Even insight or an indicator as to when files are submitted, and perhaps how large they are, would be helpful.

Tim
17,156 days

**Comment by jonquandt** [comment]
Understood - generally speaking, the time to process once submitted to GovInfo can be measured in minutes, so providing a "files submitted" time would likely not be particularly helpful.
