### ISSUE TITLE
Incorrect Session Number for Rollcalls - H.R. 8034 (118)

### ISSUE THREAD

**Issue by sam-hieken** [usgpo/bulk-data#163]
Hello,

I noticed the session number is incorrect for the rollcalls listed in [H.R. 8034 for the 118th Congress](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8034.xml). Rollcall number 152, listed in a few of the actions, should have session number 2, not 1 ("actions > item > recordedVotes > recordedVote > sessionNumber").

**Comment by llaplant** [comment]
Thank you for bringing this to our attention! The Congress.gov API Team at the Library of Congress logged the issue at https://github.com/LibraryOfCongress/api.congress.gov/issues/250, and they will publish information about the upcoming fix at https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md. After the Congress.gov API fix is deployed, GPO will reprocess the impacted Bill Status XML Bulk Data files to pull in the updated data.

**Comment by sam-hieken** [comment]
Thank you!

**Comment by apreiter18** [comment]
The Congress.gov API dev work on this has been completed. You can review this bill here: https://api.congress.gov/v3/bill/118/hr/8034/actions?api_key=INSERT_KEY (note you will need an API key to view this). Thanks!

**Comment by llaplant** [comment]
As a next step, GPO will reprocess impacted BILLSTATUS 118 files.

**Comment by sam-hieken** [comment]
Thanks for the updates guys! Going to close this as it seems resolved.
