### ISSUE TITLE
HR 3935 XML File Not Current

### ISSUE THREAD

**Issue by sibiliab** [usgpo/bulk-data#164]
The xml file hosted in the bulk data repository for HR 3935 isn't current with what's published on Congress.gov. Congress.gov says it became law on 5/16/2024. The [xml file](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr3935.xml) was last updated on 5/10 with the latest action being it passed the Senate on 5/9. Can someone please look into this? I know there are slight delays between what's published on Congress.gov and what's available in the bulk data repository, but there typically aren't two week delays. 

Thanks for your help!

**Comment by llaplant** [comment]
Thank you for letting us know. Reprocessed and updated!  

https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr3935.xml

**Comment by sibiliab** [comment]
In the bulk repository data page I'm seeing the xml file was now last updated today. The contents of the file itself though don't seem to have changed. It's still showing the latest action being it passed the Senate on 5/9. Should I expect the reprocessing changes to take effect overnight? If not, can you please take another look?

**Comment by llaplant** [comment]
Hi, I'm seeing update date of today and actions on 5/16. 

![image](https://github.com/usgpo/bulk-data/assets/11219688/e038e097-60ce-444e-b207-40739213ab3f)

![image](https://github.com/usgpo/bulk-data/assets/11219688/8e3c2be1-2d29-41f8-aac1-d34979995396)

**Comment by sibiliab** [comment]
Interesting...when I access the xml file on Chrome, I still get the older 5/10 version; however, when I access the xml file on Edge, I get the version you screenshotted above with an update date of 5/24. Maybe there's a browser compatibility issue on my end. Thank you for sharing the screenshots and reprocessing the file so quickly.

![image](https://github.com/usgpo/bulk-data/assets/13154457/fd0bf6d4-8c91-4606-afd0-024fed75cb80)
![image](https://github.com/usgpo/bulk-data/assets/13154457/9555cf59-17c8-4a68-a3e8-1a16b925d928)

**Comment by sibiliab** [comment]
Adding another note that now Chrome is showing the 5/24 xml file as well. Thanks again for your help
