### ISSUE TITLE
HR 8252 stale xml file?

### ISSUE THREAD

**Issue by sibiliab** [usgpo/bulk-data#165]
Hi,

The [xml file](https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8252.xml) in the Bulk Data Repository for HR 8252 was last modified on 6/10. The latest action date in the xml file is from 5/6 with the description being Referred to the Committee on Financial Services. [Congress.gov](https://www.congress.gov/bill/118th-congress/house-bill/8252/all-actions) has a more recent action for this bill with a date of 6/12 and a description of Referred to the Subcommittee on Economic Opportunity. I understand there can be delays between updates on Congress.gov and govinfo. Does having a six day delay indicate the xml file for HR 8252 on govinfo is not current? Or should we expect it to be updated in the next day or two?

Thanks!

**Comment by jonquandt** [comment]
@sibiliab  - this appears to be resolved. 
https://www.govinfo.gov/bulkdata/BILLSTATUS/118/hr/BILLSTATUS-118hr8252.xml is showing `<updateDate>2024-06-18T08:05:13Z</updateDate>`
