### ISSUE TITLE
2017 XML file format of 11 CFR

### ISSUE THREAD

**Issue by PaulClark2** [usgpo/bulk-data#19]
Can you tell me when the 2017 XML file format of Title 11 (11 CFR) will be available.?

https://www.gpo.gov/fdsys/bulkdata/CFR/2017

**Comment by llaplant** [comment]
We anticipate early June. Please see https://www.gpo.gov/pdfs/customers/CFR_Q1_2017.pdf and https://www.gpo.gov/customers/ofr.htm.

**Comment by PaulClark2** [comment]
Thanks!
