### ISSUE TITLE
S. 1517 Missing Introduced Date in Bill Text XML

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bulk-data#20]
Hi there, the XML bill text for S. 1517 is missing the introduced date in the GPO file and on Congress.gov:

GPO: https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/s/BILLS-115s1517is.xml
Congress.gov:  https://www.congress.gov/115/bills/s1517/BILLS-115s1517is.xml

It's available in the TXT and PDF versions of the bill text, could you please add it to the XML format? Thanks!

**Comment by llaplant** [comment]
Fixed!
