### ISSUE TITLE
Missing bills in the sitemap

### ISSUE THREAD

**Issue by edgarshvaykovsky** [usgpo/bulk-data#21]
Hello,

We have found that there is no information about several bills in the sitemap of gpo.gov.
For example, BILLS-115s1445is.xml is introduced on https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/s
but there is no such item in sitemap https://www.gpo.gov/smap/fdsys/sitemap_2017/2017_BILLS_sitemap.xml

**Comment by jonquandt** [comment]
@edgarshvaykovsky -- Thanks for bringing this to our attention. We'll take a look at it. I am going to copy/move this issue to our [sitemap repo](https://github.com/usgpo/sitemap/) for better tracking.
