### ISSUE TITLE
House Clerk's "User Guide and Data Dictionary" is outdated

### ISSUE THREAD

**Issue by jasonargoargo** [usgpo/bulk-data#28]
I'm trying to parse data from House and Senate bios from the House Clerk's and Senate Secretary's Member Data sheets (in xml format), and I noticed that the House Clerk User Guide is outdated. For instance, there are now 20 House committees instead of 19 (strangely, the Natural Resources cmte is the one missing from the User Guide), and there are 6 Joint Committees instead of 5.

Who do I talk to about getting this updated?

Link here: http://clerk.house.gov/member_info/MemberData_UserGuide.pdf

**Comment by GullicksonK** [comment]
Jason,

Thank you for this information.  I will make sure we update the table of committees shortly.

Let me also take this opportunity to tell you about a great finding aid on Congress.gov.  It is a committee name history. https://www.congress.gov/help/field-values/current-committees

Again, thank you letting us know about the error.

Kirsten Gullickson
Legislative Computer Systems | Office of the Clerk | U.S. House of Representatives

**Comment by jasonargoargo** [comment]
Wow, thank you for the lightning fast response!

**Comment by jasonargoargo** [comment]
I forgot to mention to include codes for subcommittees, as well, please! I know it says that codes for subcommittees are not unique but that won't matter for my parsing program as I can just simply change the codes with each new congress.
