### ISSUE TITLE
CFR-2009-title50 vol 8 is missing <TITLE> and <BMTR> sections

### ISSUE THREAD

**Issue by slarge** [usgpo/bulk-data#29]
https://www.gpo.gov/fdsys/bulkdata/CFR/2009/title-50/CFR-2009-title50-vol8.xml

This file is missing both the <TITLE>...</TITLE> and <BMTR>...</BMTR> sections.

**Comment by llaplant** [comment]
Taking a look...

**Comment by llaplant** [comment]
@slarge, we updated on bulk data. Could you verify? Thanks!

**Comment by slarge** [comment]
My tests confirm that the data has been corrected. Thank you!

Also, I am incredibly impressed with how quickly you addressed the problem. When I noticed the error, I did not expect that it would be solved anytime soon (let alone the same day!). Great work!
