### ISSUE TITLE
XML files available on https://www.govinfo.gov/bulkdata/BILLS/116/1/hres but not on congress.gov

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bulk-data#33]
I see resolutions on https://www.govinfo.gov/bulkdata/BILLS/116/1/hres but those same XML files are not yet available on congress. gov

E.G. 

https://www.govinfo.gov/bulkdata/BILLS/116/1/hres/BILLS-116hres3eh.xml but XML not on https://www.congress.gov/bill/116th-congress/house-resolution/3/text. (PDF is missing too even though link is available)

**Comment by llaplant** [comment]
Verified files are available on both govinfo and congress.gov.
