### ISSUE TITLE
ECFR Title 7 - Part 1773 - Subparts Duplicated?

### ISSUE THREAD

**Issue by JSimoni42** [usgpo/bulk-data#35]
Relatively new at this, so apologies for any phrasing mishaps.

I just downloaded ECFR title 7 from https://www.govinfo.gov/bulkdata/ECFR/title-7/ECFR-title7.xml and have a question regarding Part 1773 - Policy on Audits of RUS Borrowers and Grantees. It seems that the section headers begin at 1773.1 and increase up to 1773.49, as expected. However, there is another <DIV6> tag containing another Subpart A following the close of the previous <DIV6> containing Subpart E. Sections then seem to increase from 1773.1 to 1773.49, again. (See below for example)

Is this expected behavior? If so, is there more markup information that I haven't considered, to determine which set of Subparts is correct?

```
<DIV8 N="§ 1773.49" NODE="7:12.1.1.1.4.5.1.10" TYPE="SECTION">
<HEAD>§ 1773.49   OMB Control Number.</HEAD>
<P>The information collection requirements in this part are approved by the Office of Management and Budget (OMB) and assigned the OMB Control Number 0572-0095.
</P>
</DIV8>
</DIV6>

<DIV6 N="A" NODE="7:12.1.1.1.4.6" TYPE="SUBPART">
<HEAD>Subpart A - General Provisions</HEAD>
<DIV8 N="§ 1773.1" NODE="7:12.1.1.1.4.6.1.1" TYPE="SECTION">
<HEAD>§ 1773.1   General.</HEAD>
```

**Comment by llaplant** [comment]
@JSimoni42 the eCFR bulk data available at https://www.govinfo.gov/bulkdata/ECFR is created from the data that powers https://www.ecfr.gov. I see the anomaly is also present there, and I have contacted the team from the Office of the Federal Register to investigate. Thank you for bringing this to our attention!

**Comment by llaplant** [comment]
@JSimoni42 This has been corrected on eCFR.gov and should now be up to date in Bulk Data. Please verify. Thanks!

**Comment by JSimoni42** [comment]
@llaplant Apologies for the delay and thanks for the prompt response. Title 7 looks great to me! Thanks for your help.
