### ISSUE TITLE
https://www.govinfo.gov/bulkdata/BILLS/116/1/s/BILLS-116s309is.xml wrong congress

### ISSUE THREAD

**Issue by AmitElhanan** [usgpo/bulk-data#36]
https://www.govinfo.gov/bulkdata/BILLS/116/1/s/BILLS-116s309is.xml says that it is 115th congress instead of 116th. 

Data has made it to https://www.congress.gov/bill/116th-congress/senate-bill/309/text as well

**Comment by llaplant** [comment]
S. 309 IS was printed with the incorrect Congress designation. The Senate has decided not to star print S. 309 IS.
