### ISSUE TITLE
sitemapindex empty for bulkdata

### ISSUE THREAD

**Issue by mooncalfskb** [usgpo/bulk-data#37]
Hello. We are relying on this index page to determine what files to download but it is empty today. do you know what's up? 
https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/sitemapindex.xml

The sub pages that were referenced on the sitemapindex appear to still be working: 
example: https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/115s/sitemap.xml

thanks
Sherrod

**Comment by jonquandt** [comment]
thanks for reporting this issue. I'll look into it and let you know when it's resolved.

**Comment by mooncalfskb** [comment]
thanks!

**Comment by jonquandt** [comment]
We've restored an older copy of the sitemaps. I will go ahead and republish a couple of billstatus for the most recently updated billtypes in the 115th and 116th Congress. that should at least update the last modified date on the index and let you know that you should crawl them. The regular billstatus job will also trigger updates. 

Finally, coming soon  -- access to BILLSTATUS and ECFR bulkdata from our API - https://github.com/usgpo/api/issues/4

**Comment by mooncalfskb** [comment]
Great!

**Comment by JoshData** [comment]
Any update here? https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/115hr/sitemap.xml has been blank for a few days.

**Comment by jonquandt** [comment]
Let me look into that. I must have missed that one, though the others all had data in them. I’ll get back to you this morning

**Comment by jonquandt** [comment]
@JoshData - that sitemap is now restored. We're looking into how to prevent that from happening in the future. We set the update time to be this morning for all the billstatus files to ensure that no updates are missed. This does mean that there are now about 7300 billstatus packages reporting as new/updated.

**Comment by JoshData** [comment]
Thanks! I love that there are 7,300 billstatus packages to update. A few years ago there were zero! :)

**Comment by jonquandt** [comment]
reopening this issue to resolve the missing www.

**Comment by jonquandt** [comment]
@JoshData - We updated the sitemap for 115hr to include www. in the `loc` element.

**Comment by jonquandt** [comment]
Closed based on https://github.com/unitedstates/congress/issues/239 comments

**Comment by JoshData** [comment]
Thanks!

**Comment by mooncalfskb** [comment]
Thanks so much!
