### ISSUE TITLE
Bills Earlier Than 113 Congress

### ISSUE THREAD

**Issue by jox58** [usgpo/bulk-data#38]
The Congressional Bills, Bill Status and Bill Summaries only go back to 2013 (the 113th Congress). Are there any plans to add earlier archives of legislation, including their amendments and votes?

**Comment by llaplant** [comment]
@jox58 There are no plans at this time, but thank you for your suggestion. I will keep this issue open with an "enhancement" label and bring your suggestion to our legislative data partners.

**Comment by jox58** [comment]
I noticed [propubica.org](https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills) has extended their congressional bills data back to the 93rd congress --1973
