### ISSUE TITLE
500 error on Bulk Data Repository Congressional Bill Test Page

### ISSUE THREAD

**Issue by knowtheory** [usgpo/bulk-data#39]
Thanks for this Bulk Data Repository!

I was trying to check out [the test site/page](https://www.govinfo.gov/bulkdata/BILLS/test) linked to in [the Bulk Data Repository for Congressional Bills](https://www.govinfo.gov/bulkdata/BILLS), but it appears to be throwing a 500 error, and i just wanted to make certain to report it.

**Comment by jonquandt** [comment]
@knowtheory - thanks for reporting this. The directory has been deleted.
