### ISSUE TITLE
Possible to publish (additional) XSL files?

### ISSUE THREAD

**Issue by navigozane** [usgpo/bulk-data#4]
I see see the '[cfr.xml](http://www.gpo.gov/fdsys/bulkdata/CFR/resources/cfr.xsl)' XSL file to convert the CFR XML into "fancy" HTML. I wonder if there also exists an an XSL to convert the CFR XML into simple 'pre' XML text that you get [here](http://www.gpo.gov/fdsys/pkg/CFR-2014-title37-vol1/html/CFR-2014-title37-vol1.htm), and if so where is it? Or could it be posted here or in the CFR resources?

**Comment by llaplant** [comment]
The .htm file is created from native SGML that is used as part of the GPO's print production process. An XSL file does not exist for this process. You may also want to check out eCFR XML bulk data at http://www.gpo.gov/fdsys/bulkdata/ECFR. The eCFR is an editorial compilation of CFR material and Federal Register amendments produced by the Office of the Federal Register (OFR) and GPO. The OFR will update the material in the eCFR on an irregular basis that can be as frequent as every day.

**Comment by navigozane** [comment]
Thanks for the clarification.
