### ISSUE TITLE
XML files available on Govinfo.gov, not on Congress.gov

### ISSUE THREAD

**Issue by anerbovig** [usgpo/bulk-data#47]
Hello, I'm seeing a similar issue to this ticket: https://github.com/usgpo/bulk-data/issues/33

There are 92 new bill versions that have the PDF versions on the congress.gov bill pages, but do not have the XML version available that's in the bulk data repository on govinfo.gov. Is this the best place to flag the issue and have the XML versions of the text added to the congress.gov bill pages? Thank you! Listing the bills/versions below that are causing issues.

HR5347 (IH)
HR5399 (IH)
HR5401 (IH)
HR5406 (IH)
HR5407 (IH)
HR5421 (IH)
HR5422 (IH)
HR5424 (IH)
HR5425 (IH)
HR5426 (IH)
S1189 (RS)
S1310 (RS)
S2368 (RS)
S2556 (RS)
S2683 (RS)
S2688 (RS)
S2695 (RS)
S2702 (RS)
S2714 (RS)
S2977 (RS)
S3076 (RS)
HR2744 (RS)
SRES450 (ATS)
S1262 (RS)
S1890 (RS)
S2365 (RS)
S2393 (RS)
S2660 (RS)
HR4183 (RFS)
HR4719 (RFS)
SRES460 (ATS)
SRES461 (ATS)
S893 (RS)
HR4018 (PCS)
SRES456 (ATS)
S1228 (RS)
S2927 (RS)
S2799 (RS)
S2997 (RS)
SRES457 (ATS)
S2108 (RS)
S2399 (RS)
SRES459 (ATS)
SCONRES31 (ATS)
SRES152 (RS)
SRES297 (RS)
SRES343 (RS)
SRES371 (RS)
SRES375 (RS)
SRES395 (RS)
SRES447 (RS)
S876 (RS)
S1611 (RS)
S1739 (RS)
S1830 (RS)
S2425 (RS)
S2508 (RS)
S2547 (RS)
S2657 (RS)
S2668 (RS)
S3051 (RS)
HR4229 (PCS)
SRES260 (RS)
HRES767 (EH)
S1029 (ES)
S1309 (ES)
S1434 (ES)
S1822 (ES)
S1608 (ES)
S2096 (ES)
HRES773 (EH)
S3147 (ES)
HRES772 (EH)
HRES772 (RH)
HCONRES81 (ENR)
HCONRES82 (ENR)
HR1158 (ENR)
HR1865 (ENR)
HR3196 (ENR)
HR5130 (RH)
HR5146 (RH)
HR5430 (RH)
S1790 (ENR)
HR5392 (IH)
HR5393 (IH)
HR5397 (IH)
HR5398 (IH)
HR5415 (IH)
HRES768 (IH)
HRES769 (IH)
HR1865 (EAH)
HRES770 (LTH)

**Comment by jonquandt** [comment]
Good morning. This appears to have been resolved as part of normal processing. Sorry for the delay in followup.

**Comment by jonquandt** [comment]
It appears that this has been resolved as part of normal processing. There is a delay that can be expected between the xml becoming avialble on govinfo bulkdata and becoming avialable on the congress.gov site due to the need for Congress.gov to ingest the govinfo content into their system.
