### ISSUE TITLE
Possible to publish / point out amendment processing tool?

### ISSUE THREAD

**Issue by navigozane** [usgpo/bulk-data#5]
I've been searching for the tool to take the CFR XML and apply the Federal Registry proposed amendment XML to create the full CFR XML with amendments applied. Is that available somewhere? And / or could it be provided in the repo?

E.g.: [CFR Title 37](http://www.gpo.gov/fdsys/bulkdata/CFR/2014/title-37/CFR-2014-title37-vol1.xml) + [proposed amendments](https://www.federalregister.gov/articles/xml/201/520/227.xml) = proposed CFR title 37 XML

**Comment by llaplant** [comment]
Title 37 with Federal Register amendments is available at http://www.gpo.gov/fdsys/bulkdata/ECFR/title-37 and the XML User Guide is available at https://github.com/usgpo/bulk-data/blob/master/ECFR-XML-User-Guide.md. Proposed rules are contained in the Federal Register data set which is available at http://www.gpo.gov/fdsys/bulkdata/FR. The User Guide is available at https://github.com/usgpo/bulk-data/blob/master/FR-XML_User-Guide.md.

**Comment by navigozane** [comment]
Thanks for the feedback. Allow me to to clarify. I believe I've got the a handle on the current CFRs (at GPO) and the proposed / upcoming / archived amendments (at the Federal Registry). What and I understand how to manually / conceptually apply apply the amendment to the CFR.

What I want to do is to create an XML file in the same form as the GPO CFR that applies the amendment to the current rule. In other words, to produce what the CFR XML would / will look like after a proposed / future amendment is applied. We are considering writing our own tool to do this, but it seems that such a tool mst already exist (at the GPO I would guess). In other words, I want to recreate the process that updates the CFRs XMLs with amendments, but be able to do so before the amendment is actually applied to say "this is what the CFR XML will look like after / if the amendment XML is applied."

**Comment by llaplant** [comment]
A tool is not currently available from GPO to update CFR XML with proposed rules from the Federal Register. CFR SGML is updated with final rules from the Federal Register as part of the print production process. The resulting SGML is transformed to XML and made available on FDsys. You may also want to take a look at the work of http://cfpb.github.io/eRegulations/.

**Comment by navigozane** [comment]
Thanks, that clears it up.
