### ISSUE TITLE
COVID -19 Regulations Missing

### ISSUE THREAD

**Issue by raghuragz47** [usgpo/bulk-data#53]
Hi Team,

We see the COVID-19 Regulation in ECFR Website. Below are the links for reference.

https://gov.ecfr.io/cgi-bin/searchECFR?ob=r&idno=&q1=coronavirus&rgn1=Section&op2=and&q2=&rgn2=Section&op3=and&q3=&rgn3=Section&SID=70fd0c6e7b4e455aee7e767246b099cf&mc=true
https://gov.ecfr.io/cgi-bin/searchECFR?ob=r&idno=&q1=COVID&r=&SID=2a7338cb81f747e3aab8e38266bb4d1f&mc=true

But the same data is not reflected in Bulk Data.
Could you please let us know the earliest date on receiving an update for the titles 29, 17, 9, 42, 44?

**Comment by raghuragz47** [comment]
Hi Jon,

I am looking for those updates in XML Bulkdata.

**Comment by raghuragz47** [comment]
Hi Jon,

When I look at the below link. I don't see the revised versions of the titles 29, 17, 9, 42, 44.

https://www.govinfo.gov/bulkdata/CFR/2020

So I would like to know when these will be reflected in the link (https://www.govinfo.gov/bulkdata/CFR/2020).

**Comment by jonquandt** [comment]
@raghuragz47 - the /CFR endpoint for bulk data is for the annual edition of the CFR. Updates that reflect these new COVID-19 related regulations will appear in the 2020 editions published throughout the year in 2021.

The govinfo bulk data equivalent to the eCFR site is available at:
Https://www.govinfo.gov/bulkdata/ECFR.

These ECFR bulk data files are the XML equivalents of the ECFR site and represent the effect of FR final rules upon the CFR. It is an unofficial, editorial compilation

For more information on the difference between the two editions, see https://www.govinfo.gov/help/cfr

You can also use our API to get the latest updates to the ECFR collection:
https://api.govinfo.gov/collections/ECFR/2020-04-10T00:00:00Z/?pageSize=100&offset=0&api_key=DEMO_KEY

If you look at the lastModified dates, you will see the update times for those titles. For instance, title-29 was updated on
`"lastModified":"2020-04-14T00:23:23Z",`

**Comment by Cyrus-eng** [comment]
Hello my name is not Jon I have no idea who you are and there is no way for
me to identify you . please check you the intended email address that you
are trying to reach and amend accordingly thank you

**Comment by jonquandt** [comment]
@raghuragz47 - please let me know if you need any additional information regarding the ECFR bulkdata updates. Otherwise, I'll be closing this issue at the end of the day tomorrow.

**Comment by raghuragz47** [comment]
Hi Team,

Thanks for the response. I see a difference in xml formats from CFR and ECFR. Is it possible to share .xsd files for both CFR and ECFR.

Thanks,
Raghu

**Comment by jonquandt** [comment]
@raghuragz47 -- the CFR bulk data XSD is located here:
https://www.govinfo.gov/bulkdata/CFR/resources/CFRMergedXML.xsd

Currently, we don't have a publicly available version of the eCFR xsd. 

Until that becomes available, you may wish to review the [eCFR XML user guide](https://github.com/usgpo/bulk-data/blob/master/ECFR-XML-User-Guide.md) 

and the [CFR XML User Guide](https://github.com/usgpo/bulk-data/blob/master/CFR-XML_User-Guide.md)

At this point, I will close this issue. If you would like to create a separate issue related to the eCFR xsd, please do so.
