### ISSUE TITLE
Title 42, 2008 annual edition bulk data is missing volume 1 file

### ISSUE THREAD

**Issue by kaitlin** [usgpo/bulk-data#54]
All of the annual editions of title 42 seem to have a file for each volume (1-4, or 1-3 depending on the year) except 2008. 

https://www.govinfo.gov/bulkdata/CFR/2008/title-42

Is this intentional or an oversight?

Thanks in advance for looking!

**Comment by jonquandt** [comment]
Good morning,

Volume 1 of title 42 in 2008 is now available via bulk-data and the govinfo API. 

https://www.govinfo.gov/bulkdata/CFR/2008/title-42

https://www.govinfo.gov/bulkdata/CFR/2008/title-42/CFR-2008-title42-vol1.xml

**Comment by kaitlin** [comment]
Wow, awesome turnaround time! Thank you so much!
