### ISSUE TITLE
URL Loads but curl outputs API_KEY_MISSING

### ISSUE THREAD

**Issue by chrisbabayans** [usgpo/bulk-data#61]
The API key used was made for this example. 

When I open this URL in my browser, I see what I expect.

https://api.govinfo.gov/collections/CREC/2018-10-01T00:00:00Z?pageSize=10&offset=0&api_key=DEMO_KEY

The result below is when running the same URL with curl. 

` curl https://api.govinfo.gov/collections/CREC/2018-10-01T00:00:00Z?pageSize=10&offset=0&api_key=DEMO_KEY
[1] 28962
[2] 28963
[2]+  Done                    offset=0
(base) Christophers-MacBook-Pro:gov_info christopherbabayans$ {
  "error": {
    "code": "API_KEY_MISSING",
    "message": "No api_key was supplied. Get one at https://api.data.gov/signup"
  }
}`

My understanding of the API shouldn't be very far off, I was able to run the command below just fine 

`curl https://api.govinfo.gov/collections?api_key=DEMO_KEY
`

I receive the same result when trying to curl the below collections which I am able to view in the browser as expected.

https://api.govinfo.gov/collections/BILLS/2018-10-01T00:00:00Z?pageSize=10&offset=0&api_key=DEMO_KEY

& 

https://api.govinfo.gov/collections/BILLSTATUS/2018-10-01T00:00:00Z?pageSize=10&offset=0&api_key=DEMO_KEY

**Comment by jonquandt** [comment]
updated the issue above to reference the DEMO_KEY. I was able to reproduce using that, and it would be preferable to not have an normal API key shown in the repo.

**Comment by jonquandt** [comment]
@chrisbabayans  -- I have identified the issue. You need to enclose the address in your request in double quotes (`"`).

See this equivalent request:

```
$ curl "https://api.govinfo.gov/collections/CREC/2018-10-01T00:00:00Z?pageSize=10&offset=0&api_key=DEMO_KEY"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2998    0  2998    0     0   2781      0 --:--:--  0:00:01 --:--:--  2953{"count":4726,"message":null,"nextPage":"https://api.govinfo.gov/collections/CREC/2018-10-01T00:00:00Z?offset=10&pageSize=10","previousPage":null,"packages":[{"packageId":"CREC-2020-07-28","lastModified":"2020-07-29T09:01:13Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-28/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 133, (July 28, 2020)","congress":"116","dateIssued":"2020-07-28T12:00:00Z"},{"packageId":"CREC-2020-07-23","lastModified":"2020-07-28T12:19:28Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-23/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 130, (July 23, 2020)","congress":"116","dateIssued":"2020-07-23T12:00:00Z"},{"packageId":"CREC-2020-07-27","lastModified":"2020-07-28T10:34:43Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-27/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 132, (July 27, 2020)","congress":"116","dateIssued":"2020-07-27T12:00:00Z"},{"packageId":"CREC-2020-07-24","lastModified":"2020-07-25T09:54:09Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-24/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 131, (July 24, 2020)","congress":"116","dateIssued":"2020-07-24T12:00:00Z"},{"packageId":"CREC-2014-03-13","lastModified":"2020-07-24T16:01:04Z","packageLink":"https://api.govinfo.gov/packages/CREC-2014-03-13/summary","docClass":"CREC","title":"Congressional Record Volume 160, Issue 42, (March 13, 2014)","congress":"113","dateIssued":"2014-03-13T12:00:00Z"},{"packageId":"CREC-2020-07-09","lastModified":"2020-07-24T16:00:29Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-09/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 124, (July 9, 2020)","congress":"116","dateIssued":"2020-07-09T12:00:00Z"},{"packageId":"CREC-2020-07-22","lastModified":"2020-07-24T00:29:24Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-22/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 129, (July 22, 2020)","congress":"116","dateIssued":"2020-07-22T12:00:00Z"},{"packageId":"CREC-2020-07-21","lastModified":"2020-07-22T15:25:43Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-21/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 128, (July 21, 2020)","congress":"116","dateIssued":"2020-07-21T12:00:00Z"},{"packageId":"CREC-2020-07-20","lastModified":"2020-07-21T21:32:22Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-20/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 127, (July 20, 2020)","congress":"116","dateIssued":"2020-07-20T12:00:00Z"},{"packageId":"CREC-2020-07-16","lastModified":"2020-07-17T10:10:50Z","packageLink":"https://api.govinfo.gov/packages/CREC-2020-07-16/summary","docClass":"CREC","title":"Congressional Record Volume 166, Issue 126, (July 16, 2020)","congress":"116","dateIssued":"2020-07-16T12:00:00Z"}]}
```

if you do a curl -v with your original request, you can see that what gets sent to the server is the following:

GET /collections/CREC/2018-10-01T00:00:00Z?pageSize=10 HTTP/1.1
> Host: api.govinfo.gov
> User-Agent: curl/7.54.0
> Accept: */*

the `[1] 28962 [2] 28963 [2]+` in your ouput above indicates that the curl command is dropping the parameters after the `&` operators.

From the [curl man page](https://curl.haxx.se/docs/manpage.html):

> When using [] or {} sequences when invoked from a command line prompt, you probably have to put the full URL within double quotes to avoid the shell from interfering with it. This also goes for other characters treated special, like for example '&', '?' and '*'.
