### ISSUE TITLE
Bulkdata crawling returns 406 error

### ISSUE THREAD

**Issue by ogtega** [usgpo/bulk-data#67]
Is the 406 error I get when using python to crawl bulkdata JSON URLs intentional?

**Comment by ogtega** [comment]
It seems this is due to Cloudflare not supporting dynamic content, I had to add `Accept: application/json` to my headers.

**Comment by jonquandt** [comment]
@ogtega  - sorry for the delayed response. Yes, the Accept headers are required.  I'll make a note in the documentation.
