### ISSUE TITLE
Missing titles in CFR 2020

### ISSUE THREAD

**Issue by gunnerwholelife** [usgpo/bulk-data#77]
source - https://www.govinfo.gov/app/collection/cfr/2020/ OR https://www.govinfo.gov/bulkdata/CFR/2020

There are many missing titles in the latest CFR 2020 release.
Titles missing - 3, 30,31, 32, 33, 35, 36, 37, 38, 39

1. Any idea when these titles will be released ?
2. Is there a documentation on why some titles are missing in some years (In 2019 CFR release, title 35 was missing.)
3. And is it safe to assume there are no changes from previous years if the titles are missing ?

Thanks.

**Comment by jonquandt** [comment]
@gunnerwholelife  -- from https://www.govinfo.gov/help/cfr:

> When is it updated?
>The CFR on govinfo is current with the published print version of the CFR. When the print editions are released, the online version is also made available. If a CFR Title or volume is not listed in the CFR browse, that volume has not yet been published.
>The 50 subject matter titles contain one or more individual volumes, which are updated once each calendar year, on a staggered basis. The annual update cycle is as follows:
>- titles 1-16 are revised as of January 1
>- titles 17-27 are revised as of April 1
>- titles 28-41 are revised as of July 1
>- titles 42-50 are revised as of October 1


There is typically a delay between the revision date and the titles being made available. The revision date is essentially a cut-off point for the snapshot of the CFR volume for that year. More info on that can be found at https://www.govinfo.gov/help/cfr#faqs

A more timely view of the CFR is available through the eCFR bulkdata collection (also available via the API).

I'm checking in to verify a few things regarding your specific questions.

There is a c

**Comment by jonquandt** [comment]
Update:

1. CFR volumes are published after the revision and compilation of changes are completed. There is usually a delay of some weeks to months before this is complete, depending on the complexity of the revisions. I don't have any sense of when the titles you mentioned would be available at this time. **Note:** CFR Title 3 volume 1 was made available in August of 2020 -- https://api.govinfo.gov/packages/CFR-2020-title3-vol1/summary?api_key=DEMO_KEY 
2. In the specific instance you mention, Title 35 pertains to the Panama Canal, and is now currently a reserved title. the last true update to that title occurred in 2000.  See https://www.govinfo.gov/app/details/CFR-2000-title35-vol1/
3.  Until a CFR volume is published, it would _not_ be safe to assume that there are not changes. One way to see if there are no changes would be to check the MODS metadata for the given package to see if it has a `isCoverOnly` value of true. If that is the case, then the only change to the title is that a new cover is available for the same content.

As I mentioned, you may be interested in looking at the eCFR collection via the bulkdata repository or via the API. The eCFR is "a regularly updated, unofficial editorial compilation of CFR material and Federal Register amendments. The eCFR is updated on a daily basis." (again, from the govinfo CFR help page). This essentially means that the eCFR takes the most recent annual snapshot of the CFR and applies changes to it based on final rules issued within the Federal Register. While unofficial, it should serve as a good guide related to updates

I hope this is helpful.

**Comment by gunnerwholelife** [comment]
Thanks @jonquandt 
This is very helpful.

I have follow up questions -
1. Under the bulk data -
   -- what's the difference between title-x-vol1.xml and say title-x-vol2.xml ? eg: https://www.govinfo.gov/bulkdata/CFR/2020/title-12

2. Are you working in collaboration with federalregister for ecfr api - https://ecfr.federalregister.gov/
   -- If yes, is there a github repository I can take look at ? I couldn't find it anywhere.

**Comment by jonquandt** [comment]
@gunnerwholelife  - 

1. CFR packages on govinfo are broken up into volumes, to match the tangible/printed version of the CFR.
2. I'm not specifically aware of a github repository for the ecfr.federalregister.gov API, Their interactive documentation is available here: https://ecfr.federalregister.gov/developers/documentation/api/v1. 

You may wish to submit feedback for their API via the feedback button on the bottom right of each screen. The eCFR data presented on ecfr.federalregister.gov is based on the eCFR xml files available from the govinfo API and bulk data site. GPO works in partnership with the Office of the Federal Register to support and administer the ecfr.federalregister.gov site.

The ecfr.federalregister.gov site does provide some useful value added functionality that you would likely find to be helpful.

**Comment by LahyanDjeh** [comment]
Okay I only created a Github accounts and still unable to integrate the
apps. I've just created the federal register account using the link u sent

**Comment by gunnerwholelife** [comment]
@jonquandt Thanks a ton ! Please close this issue as I have received the necessary info. I didn't close it myself as I was unsure of the above comment. :S
I also opened a new issue for the api repo [here](https://github.com/usgpo/api/issues/78)
Would appreciate your feedback there.

**Comment by jonquandt** [comment]
@LahyanDjeh  - I am closing this issue. Can you open a separate issue with more details if you need assistance? 

Thanks!

**Comment by LahyanDjeh** [comment]
Thank you so much. Thank you. How and where through which app on my website
can I use on managing my searches and bookmarking , saving and maybe share
likes
