### ISSUE TITLE
Timing of Updates

### ISSUE THREAD

**Issue by Skekacs93** [usgpo/bulk-data#8]
What time have the bulk updates been being pushed to the site each morning? It seems like they've been moving progressively later.

**Comment by llaplant** [comment]
Update times are different for each collection and are generally related to the timing of print publication workflows. Are you pulling a specific data set?

**Comment by Skekacs93** [comment]
I'm mainly looking at the BILLSTATUS bulk uploads, my main concern is that it seems like some updates from yesterday (27th) are not showing (eg: https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr/BILLSTATUS-114hr5303.xml).

**Comment by llaplant** [comment]
Some of the updates initially failed for the 8 am job and we had to rerun. Looking at specific one you mentioned now...

**Comment by llaplant** [comment]
@Skekacs93 how's it looking from your perspective? Looks like a number of updates to 5303 were pulled in with the noon job yesterday.

**Comment by Skekacs93** [comment]
Yup got them in, thanks for the help. Is there a reason those updates weren't in earlier in the morning?

**Comment by llaplant** [comment]
I'll have to dig a little deeper on that question. Two possibilities are either the data was not available for us to consume in the 8 am job or the issues we were experiencing with 8 am job caused the file to not be updated.

**Comment by Skekacs93** [comment]
Great, thank you!
