### ISSUE TITLE
CFR10 Missing images

### ISSUE THREAD

**Issue by ThomasShafron** [usgpo/bulk-data#83]
Hello, 
my name is Tom. My current task at work involves me using the information provided by this page: https://www.govinfo.gov/bulkdata/ECFR/title-10
to generate an html version of the title 10 case. 

I have noticed that there are quite a few missing images that are being referenced by the XML document which are not contained in the zip file of images that accompanies the xml. 

An example of a few of those images includes:

![image](https://user-images.githubusercontent.com/84492538/118924550-99aaeb80-b980-11eb-8db4-4bf424d8c0cc.png)

These images do not seem to be present in the zip folder, however, when looking at the CFR10 case as presented on this part of the website the images do seem to be properly present: https://ecfr.federalregister.gov/current/title-10/chapter-II/subchapter-D/part-430#Appendix-M-to-Subpart-B-of-Part-430

![image](https://user-images.githubusercontent.com/84492538/118925039-58ffa200-b981-11eb-81f1-3c69adb9f481.png)

Was wondering if the zip file with the images could be updated to contain all the referenced images, or am I doing something wrong? 

Regards. 

Tom

**Comment by jonquandt** [comment]
@ThomasShafron can you confirm that you’re not seeing the images in the accompanying graphics zip file?

https://www.govinfo.gov/bulkdata/ECFR/title-10/ECFR-title10-graphics.zip

**Comment by Hoove391** [comment]
No updates are being made

**Comment by ThomasShafron** [comment]
@jonquandt thanks for responding. That is correct. 

Some images that I see are referenced by the XML but don't exist in https://www.govinfo.gov/bulkdata/ECFR/title-10/ECFR-title10-graphics.zip are all images which have prefix er05ja17. For example:
- er05ja17.004.gif
- er05ja17.005.gif
- er05ja17.006.gif

**Comment by Hoove391** [comment]
They are not visual but I can see some

**Comment by jonquandt** [comment]
We're in the process of reconciling the graphics with the XML across all titles. I hope to have an update soon on when an updated title 10 is available.

**Comment by ThomasShafron** [comment]
Great! Thanks for looking into it :) I look forward to your update

**Comment by jonquandt** [comment]
@ThomasShafron  -- actually, it appears that the graphics have been updated for title 10, as well as 16 other titles. 

https://api.govinfo.gov/collections/ECFR/2021-05-21T20:15:00Z?pageSize=50&offset=0&api_key=DEMO_KEY

I verified that the graphics folder has the additional graphics that you listed above, as well as others that were previously missing. Please review and let me know if you have any further issues.

**Comment by ThomasShafron** [comment]
Great. Just confirmed that all the images now exist in that zip. Thanks for your help :)
