### ISSUE TITLE
Text for HR 3241

### ISSUE THREAD

**Issue by DaGenix** [usgpo/bulk-data#90]
I'm expecting to find the text of HR 3241 from the 117th congress here: https://www.govinfo.gov/bulkdata/BILLS/117/1/hr/BILLS-117hr3241ih.xml. However, that file doesn't seem to exist and I can't find it in the bulk data .zip file either. Curious if that was the right place to look and/or if it missing for some reason. Thanks!

**Comment by llaplant** [comment]
H.R. 3241 is a "codification measure." At this time, codification measures are not available in XML. The XML is not be expected to be available from govinfo or Congress.gov, but text and PDF formats along with XML metadata is available at https://www.govinfo.gov/app/details/BILLS-117hr3241ih. Information about known data anomalies can be found at https://www.congress.gov/help/data-anomalies.

**Comment by DaGenix** [comment]
Ah, cool, thanks so much for your assistance!
