### ISSUE TITLE
Bill Digest Missing

### ISSUE THREAD

**Issue by cmenard9** [usgpo/bulk-data#93]
https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr

There has not been any bill information listed in December at Gov info. There were many introduced that i can see at congress.gov https://www.congress.gov/search?q=%7B%22source%22%3A%22legislation%22%7D

Could someone please look into why govinfo does not have any information past 11/30/2021 at the above link.

Thank you

**Comment by llaplant** [comment]
Please see https://github.com/usgpo/bill-status/issues/185. We hope to have service restored on Friday.

**Comment by cmenard9** [comment]
Thank you!

**Comment by llaplant** [comment]
Closing issue because service was restored.
