### ISSUE TITLE
Vol 1 and 2 Missing from the 2021 19 CFR

### ISSUE THREAD

**Issue by aquabox** [usgpo/bulk-data#94]
Trying to download the XML for the 2021 version of 19 CFR but only volume 3 is present.  Can Volumes 1 and 2 be made available?

**Comment by llaplant** [comment]
Checking with other areas in GPO for estimate of when volumes 1 and 2 will be published and then submitted to govinfo.

**Comment by llaplant** [comment]
Volumes 1 and 2 are now available.
https://www.govinfo.gov/bulkdata/CFR/2021/title-19
